import { AnimationsHandler } from "./scripts/modules/animations.mjs";
import { SheetEdits } from "./scripts/modules/applications/sheetEdits.mjs";
import { CombatEnhancements } from "./scripts/modules/combatHelpers.mjs";
import ActorSheet5eCharacter from "./scripts/modules/documents/character-sheet.mjs";
import ActorExtension from "./scripts/modules/documents/character.mjs";
import { ExhaustionHandler } from "./scripts/modules/exhaustion.mjs";
import { GameChangesHandler } from "./scripts/modules/gameChanges.mjs";
import PublicAPI from "./scripts/modules/publicAPI.mjs";
import { SocketsHandler } from "./scripts/modules/sockets.mjs";
import ModuleSettings from "./scripts/settings.mjs";

Hooks.once("init", ActorExtension.init);
Hooks.once("init", ActorSheet5eCharacter.init);
Hooks.once("init", AnimationsHandler.init);
Hooks.once("init", CombatEnhancements.init);
Hooks.once("init", ExhaustionHandler.init);
Hooks.once("init", GameChangesHandler.init);
Hooks.once("init", ModuleSettings.init);
Hooks.once("init", PublicAPI.init);
Hooks.once("init", SheetEdits.init);
Hooks.once("init", SocketsHandler.init);
